dist: bionic

language: go

go:
  - 1.13.x

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get golang.org/x/lint/golint

before_script:
  - psql -U postgres -c 'CREATE DATABASE go_restful;';

script:
  - make lint
  - make build
  - make test
  - $HOME/gopath/bin/goveralls -coverprofile=coverage-all.out -service=travis-ci
